repos:
  - repo: local
    hooks:
      - id: freeze-requirements
        name: Freeze requirements into requirements.txt
        entry: sh -c "uv pip freeze > requirements.txt"
        language: system
        always_run: true