version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ciao1234
      POSTGRES_USER: vanni
      POSTGRES_DB: fl-db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data 
    ports:
      - 5432:5432
volumes:
  postgres-data:
  